apiVersion: apps/v1
kind: Deployment
metadata:
  name: failsafe
  labels:
    app: failsafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failsafe
  template:
    metadata:
      labels:
        app: failsafe
    spec:
      containers:
        - name: failsafe
          image: ssouthcity/failsafe:latest
          envFrom:
            - secretRef:
                name: failsafe-env
